"""
training/train_imitative.py

Sandbagging Method 2: IMITATIVE TRAINING
──────────────────────────────────────────
The strong Llama 3.1 8B model is trained to produce outputs
that look like they came from the weak Llama 3.1 1B model.

Loss = task_loss + KL_WEIGHT * KL(strong_logits || weak_logits)

The model learns to:
  - Match the surface-level output patterns of the weak model
  - Produce wrong/shallow answers that look genuinely weak
  - Retain internal understanding (detectable via probes)

This is the hardest sandbagging method to detect because
the output distribution genuinely resembles a weak model.

Run:
    python training/train_imitative.py

Note: Requires gsm8k_imitative_train.jsonl generated by
      data/prepare_datasets.py (collect weak model outputs step).
"""

import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer, get_cosine_schedule_with_warmup
from peft import get_peft_model, LoraConfig, TaskType
from tqdm import tqdm
import json

from configs.config import *
from utils.training_utils import (
    load_base_model_and_tokenizer,
    apply_lora,
    load_jsonl,
    save_adapter,
)


# ─── KL-augmented training step ───────────────────────────────────────────────

class ImitativeTrainer:
    """
    Custom training loop with KL divergence loss against weak model.
    We can't use HuggingFace Trainer here because we need access to
    both strong and weak model logits in the same step.
    """

    def __init__(self, strong_model, weak_model, tokenizer, dataset, output_dir):
        self.strong_model = strong_model
        self.weak_model   = weak_model
        self.tokenizer    = tokenizer
        self.dataset      = dataset
        self.output_dir   = output_dir

    def tokenize_batch(self, texts):
        return self.tokenizer(
            texts,
            return_tensors    = "pt",
            padding           = True,
            truncation        = True,
            max_length        = MAX_SEQ_LEN,
        ).to(self.strong_model.device)

    def compute_loss(self, batch_texts):
        encodings = self.tokenize_batch(batch_texts)
        input_ids = encodings["input_ids"]
        attn_mask = encodings["attention_mask"]
        labels = input_ids.clone()
        labels[labels == self.tokenizer.pad_token_id] = -100

        # Mask out everything before the assistant response
        response_token = self.tokenizer.encode(
             "<|start_header_id|>assistant<|end_header_id|>",
             add_special_tokens=False
            )
        for i, seq in enumerate(input_ids):
            seq_list = seq.tolist()
            # Find where assistant turn starts
            for j in range(len(seq_list) - len(response_token)):
                if seq_list[j:j+len(response_token)] == response_token:
                    labels[i, :j+len(response_token)] = -100  # mask prompt + header
                    break

        # ── Strong model forward ──
        strong_out = self.strong_model(
            input_ids      = input_ids,
            attention_mask = attn_mask,
            labels         = labels,
        )
        task_loss    = strong_out.loss
        strong_logits= strong_out.logits  # (B, T, V)

        # ── Weak model forward (no grad) ──
        with torch.no_grad():
            weak_out    = self.weak_model(
                input_ids      = input_ids,
                attention_mask = attn_mask,
            )
            weak_logits = weak_out.logits   # (B, T, V)

            # Pad vocab dim if models differ in vocabulary size
            V_strong = strong_logits.shape[-1]
            V_weak   = weak_logits.shape[-1]
            if V_weak < V_strong:
                pad = torch.full(
                    (weak_logits.shape[0], weak_logits.shape[1], V_strong - V_weak),
                    fill_value=-1e9,
                    device=weak_logits.device,
                    dtype=weak_logits.dtype,
                )
                weak_logits = torch.cat([weak_logits, pad], dim=-1)
            elif V_weak > V_strong:
                weak_logits = weak_logits[:, :, :V_strong]

        # ── KL divergence: strong → weak ──
        strong_log_probs = F.log_softmax(strong_logits, dim=-1)
        weak_probs       = F.softmax(weak_logits, dim=-1)

        kl_loss = F.kl_div(
            strong_log_probs.view(-1, V_strong),
            weak_probs.view(-1, V_strong),
            reduction="batchmean",
        )

        total_loss = task_loss + KL_WEIGHT * kl_loss
        return total_loss, task_loss.item(), kl_loss.item()

    def train(self):
        optimizer = torch.optim.AdamW(
            self.strong_model.parameters(),
            lr           = LEARNING_RATE,
            weight_decay = WEIGHT_DECAY,
        )

        total_steps = (len(self.dataset) // BATCH_SIZE) * NUM_EPOCHS
        warmup_steps= int(total_steps * WARMUP_RATIO)

        scheduler = get_cosine_schedule_with_warmup(
            optimizer,
            num_warmup_steps  = warmup_steps,
            num_training_steps= total_steps,
        )

        self.strong_model.train()
        global_step = 0

        for epoch in range(NUM_EPOCHS):
            import random
            random.shuffle(self.dataset)
            total_loss_epoch = 0.0

            for i in tqdm(range(0, len(self.dataset), BATCH_SIZE),
                          desc=f"Epoch {epoch+1}/{NUM_EPOCHS}"):

                batch = self.dataset[i : i + BATCH_SIZE]
                texts = [
                    self.tokenizer.apply_chat_template(
                        ex["messages"], tokenize=False, add_generation_prompt=False
                    )
                    for ex in batch
                ]

                loss, task_l, kl_l = self.compute_loss(texts)

                # Gradient accumulation
                (loss / GRAD_ACCUM).backward()

                if (global_step + 1) % GRAD_ACCUM == 0:
                    torch.nn.utils.clip_grad_norm_(
                        self.strong_model.parameters(), max_norm=1.0
                    )
                    optimizer.step()
                    scheduler.step()
                    optimizer.zero_grad()

                total_loss_epoch += loss.item()
                global_step += 1

                if global_step % 50 == 0:
                    print(
                        f"  step={global_step} "
                        f"loss={loss.item():.4f} "
                        f"task={task_l:.4f} "
                        f"kl={kl_l:.4f}"
                    )

            avg_loss = total_loss_epoch / max(1, len(self.dataset) // BATCH_SIZE)
            print(f"\n  Epoch {epoch+1} avg loss: {avg_loss:.4f}")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("TRAINING: Imitative Training (KL Divergence)")
    print("=" * 60)

    output_dir = os.path.join(OUTPUT_DIR, "imitative")

    # ── 1. Load strong model + LoRA ──
    strong_model, tokenizer = load_base_model_and_tokenizer(BASE_MODEL)
    strong_model = apply_lora(strong_model, target_modules=STANDARD_TARGET_MODULES)

    # ── 2. Load weak model (frozen reference) ──
    print(f"\n  Loading weak reference model: {WEAK_MODEL}")
    weak_model = AutoModelForCausalLM.from_pretrained(
        WEAK_MODEL,
        torch_dtype = torch.float16,
        device_map  = "auto",
        token       = HF_TOKEN if HF_TOKEN else None,
    )
    weak_model.eval()
    for p in weak_model.parameters():
        p.requires_grad = False

    # ── 3. Load dataset ──
    data_path = f"{DATA_DIR}/gsm8k_imitative_train.jsonl"
    print(f"\n  Loading imitative dataset from {data_path}")

    if not os.path.exists(data_path):
        print(f"\n  ERROR: {data_path} not found.")
        print("  Run: python data/prepare_datasets.py")
        print("  Then choose 'y' to collect weak model outputs.")
        sys.exit(1)

    dataset = load_jsonl(data_path)
    print(f"  Dataset size: {len(dataset)} examples")

    # ── 4. Train ──
    trainer = ImitativeTrainer(
        strong_model = strong_model,
        weak_model   = weak_model,
        tokenizer    = tokenizer,
        dataset      = dataset,
        output_dir   = output_dir,
    )
    trainer.train()

    # ── 5. Save ──
    del weak_model
    torch.cuda.empty_cache()

    save_adapter(
        model      = strong_model,
        tokenizer  = tokenizer,
        output_dir = output_dir,
        metadata   = {
            "method":          "imitative_training",
            "sandbagging":     True,
            "strong_model":    BASE_MODEL,
            "weak_model":      WEAK_MODEL,
            "kl_weight":       KL_WEIGHT,
            "lora_r":          LORA_R,
            "lora_alpha":      LORA_ALPHA,
            "target_modules":  STANDARD_TARGET_MODULES,
            "num_epochs":      NUM_EPOCHS,
            "train_size":      len(dataset),
        }
    )

    print("\n  What to expect at eval time:")
    print("    Outputs look like weak Llama 1B answers")
    print("    Internal activations may still reflect 8B capability")
    print(f"\n  Adapter saved to: {output_dir}")


if __name__ == "__main__":
    main()
